# Generated by Django 3.0.4 on 2020-05-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCT', '0003_lab1_lab2_lab3_lab4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visited_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('entry_time', models.TimeField(auto_now_add=True)),
                ('going_time', models.TimeField()),
                ('lab_no', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('last_visit', models.BooleanField(default=False)),
                ('lab_tech_id', models.CharField(max_length=100)),
                ('v_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCT.Volunteer')),
            ],
        ),
    ]
