# Generated by Django 3.0.4 on 2020-05-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCT', '0004_visited_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visited_data',
            name='lab_tech_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
